### ISSUE TITLE
1.12.2 source?

### ISSUE THREAD

**Issue by xJon** [ManGregory128/asgardshieldreloaded#2]
Would be nice to have for possible PRs or forks considering the mod is open source :)

**Comment by xJon** [comment]
Thank you @ACGaming <3

**Comment by ManGregory128** [comment]
Thank you for revitalising the 1.12.2 version! I never posted the code here since to be honest it was not much to begin with (I never managed to get the swords to block like shields). Please let me know if I can help in any way and of course you can have access to the project on CurseForge! I will start working on the mod again as soon as my uni exams are over in a month :)
